//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizeApplication.Resources.Localization{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpressMaui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpressMaui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizeApplication.Resources.Localization.DevExpressMaui", typeof(DevExpressMaui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string CollectionViewStringId_GroupCaptionDisplayFormat {
            get {
                return ResourceManager.GetString("CollectionViewStringId.GroupCaptionDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string CollectionViewStringId_GroupIntervalMonthDisplayFormat {
            get {
                return ResourceManager.GetString("CollectionViewStringId.GroupIntervalMonthDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string CollectionViewStringId_GroupIntervalYearDisplayFormat {
            get {
                return ResourceManager.GetString("CollectionViewStringId.GroupIntervalYearDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older;Last Month;Earlier this Month;Three Weeks Ago;Two Weeks Ago;Last Week;;;;;;;;Yesterday;Today;Tomorrow;;;;;;;;Next Week;Two Weeks Away;Three Weeks Away;Later this Month;Next Month;Beyond Next Month;.
        /// </summary>
        internal static string CollectionViewStringId_OutlookIntervals {
            get {
                return ResourceManager.GetString("CollectionViewStringId.OutlookIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string EditorStringId_ComboBox_NotFound {
            get {
                return ResourceManager.GetString("EditorStringId.ComboBox_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input value.
        /// </summary>
        internal static string EditorStringId_DataForm_ValidationExceptionMessage {
            get {
                return ResourceManager.GetString("EditorStringId.DataForm_ValidationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string EditorStringId_DateEdit_Picker_CANCEL {
            get {
                return ResourceManager.GetString("EditorStringId.DateEdit_Picker_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EditorStringId_DateEdit_Picker_OK {
            get {
                return ResourceManager.GetString("EditorStringId.DateEdit_Picker_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        internal static string GridStringId_Caption_SummaryAverage {
            get {
                return ResourceManager.GetString("GridStringId.Caption_SummaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        internal static string GridStringId_Caption_SummaryCount {
            get {
                return ResourceManager.GetString("GridStringId.Caption_SummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL.
        /// </summary>
        internal static string GridStringId_Caption_SummaryCustom {
            get {
                return ResourceManager.GetString("GridStringId.Caption_SummaryCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        internal static string GridStringId_Caption_SummaryMax {
            get {
                return ResourceManager.GetString("GridStringId.Caption_SummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        internal static string GridStringId_Caption_SummaryMin {
            get {
                return ResourceManager.GetString("GridStringId.Caption_SummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string GridStringId_Caption_SummaryNone {
            get {
                return ResourceManager.GetString("GridStringId.Caption_SummaryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string GridStringId_Caption_SummarySum {
            get {
                return ResourceManager.GetString("GridStringId.Caption_SummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Values.
        /// </summary>
        internal static string GridStringId_EditorFormPage_EditValues {
            get {
                return ResourceManager.GetString("GridStringId.EditorFormPage_EditValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GridStringId_EditorFormPage_Save {
            get {
                return ResourceManager.GetString("GridStringId.EditorFormPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older;Last Month;Earlier this Month;Three Weeks Ago;Two Weeks Ago;Last Week;;;;;;;;Yesterday;Today;Tomorrow;;;;;;;;Next Week;Two Weeks Away;Three Weeks Away;Later this Month;Next Month;Beyond Next Month;.
        /// </summary>
        internal static string GridStringId_GridOutlookIntervals {
            get {
                return ResourceManager.GetString("GridStringId.GridOutlookIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string GridStringId_GroupCaptionDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupCaptionDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string GridStringId_GroupIntervalMonthDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupIntervalMonthDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string GridStringId_GroupIntervalYearDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupIntervalYearDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}={2}.
        /// </summary>
        internal static string GridStringId_GroupSummaryCountDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupSummaryCountDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}: {0}={2}.
        /// </summary>
        internal static string GridStringId_GroupSummaryDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupSummaryDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string GridStringId_GroupSummaryShortDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupSummaryShortDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}={2}.
        /// </summary>
        internal static string GridStringId_TotalSummaryDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.TotalSummaryDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Day {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Days {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Hour {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Hours {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Minute {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Minutes {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Week {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string SchedulerStringId_Abbr_Weeks {
            get {
                return ResourceManager.GetString("SchedulerStringId.Abbr_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string SchedulerStringId_Appointment_Label {
            get {
                return ResourceManager.GetString("SchedulerStringId.Appointment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string SchedulerStringId_Appointment_Reminder {
            get {
                return ResourceManager.GetString("SchedulerStringId.Appointment_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SchedulerStringId_Appointment_Status {
            get {
                return ResourceManager.GetString("SchedulerStringId.Appointment_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat {0}.
        /// </summary>
        internal static string SchedulerStringId_AppointmentDetailFormat_Recurrence {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentDetailFormat_Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        internal static string SchedulerStringId_AppointmentDetailFormat_Status {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentDetailFormat_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_AcceptAppointmentRemoveAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_AcceptAppointmentRemoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_CancelAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_CancelAppointmentRemoveAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_CancelAppointmentRemoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Appointment.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_EditAppointmentTitle {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change this and all future appointments.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_EditFutureOccurrencesAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditFutureOccurrencesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change this appointment only.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_EditOccurrenceAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditOccurrenceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change all appointments in the series.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_EditPatternAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditPatternAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_NewAppointmentTitle {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_NewAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Customization.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_ReminderCustomization {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_ReminderCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete appointment?.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_RemoveAppointmentTitle {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemoveAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this and all future appointments.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_RemoveFutureOccurrencesAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemoveFutureOccurrencesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this appointment only.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_RemoveOccurrenceAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemoveOccurrenceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all appointments in the series.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_RemovePatternAction {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemovePatternAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a recurring appointment..
        /// </summary>
        internal static string SchedulerStringId_AppointmentEdit_SelectAppointmentTypeTitle {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEdit_SelectAppointmentTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another reminder.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEditPage_AddAnotherReminder {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_AddAnotherReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a reminder.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEditPage_AddReminder {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEditPage_AllDay {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEditPage_Label {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEditPage_Repeat {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEditPage_Status {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment name.
        /// </summary>
        internal static string SchedulerStringId_AppointmentEditPage_SubjectPlaceholder {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_SubjectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_Anniversary {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_Birthday {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_Business {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_Important {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Attend.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_MustAttend {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_MustAttend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Preparation.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_NeedsPreparation {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_NeedsPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_None {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_Personal {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Call.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_PhoneCall {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_PhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Required.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_TravelRequired {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_TravelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        internal static string SchedulerStringId_AppointmentLabel_Vacation {
            get {
                return ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string SchedulerStringId_Caption_Busy {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string SchedulerStringId_Caption_Free {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Office.
        /// </summary>
        internal static string SchedulerStringId_Caption_OutOfOffice {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_OutOfOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        internal static string SchedulerStringId_Caption_Tentative {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_Tentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekDaysEveryDay {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekDaysEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend day.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekDaysWeekendDays {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekDaysWeekendDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekDaysWorkDays {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekDaysWorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekOfMonthFirst {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekOfMonthFourth {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekOfMonthLast {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekOfMonthSecond {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string SchedulerStringId_Caption_WeekOfMonthThird {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Elsewhere.
        /// </summary>
        internal static string SchedulerStringId_Caption_WorkingElsewhere {
            get {
                return ResourceManager.GetString("SchedulerStringId.Caption_WorkingElsewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string SchedulerStringId_CommonRadioGroup_After {
            get {
                return ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string SchedulerStringId_CommonRadioGroup_Never {
            get {
                return ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurrence(s).
        /// </summary>
        internal static string SchedulerStringId_CommonRadioGroup_Occurrences {
            get {
                return ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string SchedulerStringId_CommonRadioGroup_On {
            get {
                return ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string SchedulerStringId_DayRadioGroup_DayOrDays {
            get {
                return ResourceManager.GetString("SchedulerStringId.DayRadioGroup_DayOrDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string SchedulerStringId_DayRadioGroup_Every {
            get {
                return ResourceManager.GetString("SchedulerStringId.DayRadioGroup_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every weekday.
        /// </summary>
        internal static string SchedulerStringId_DayRadioGroup_EveryWeekDay {
            get {
                return ResourceManager.GetString("SchedulerStringId.DayRadioGroup_EveryWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string SchedulerStringId_MonthRadioGroup_DayOrDays {
            get {
                return ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_DayOrDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each.
        /// </summary>
        internal static string SchedulerStringId_MonthRadioGroup_Each {
            get {
                return ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string SchedulerStringId_MonthRadioGroup_MonthOrMonths {
            get {
                return ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_MonthOrMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of every.
        /// </summary>
        internal static string SchedulerStringId_MonthRadioGroup_OfEvery {
            get {
                return ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        internal static string SchedulerStringId_MonthRadioGroup_The {
            get {
                return ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid day of week for a daily recurrence. Only WeekDays.EveryDay, WeekDays.WeekendDays and WeekDays.WorkDays are valid in this context..
        /// </summary>
        internal static string SchedulerStringId_Msg_InvalidDayOfWeekForDailyRecurrence {
            get {
                return ResourceManager.GetString("SchedulerStringId.Msg_InvalidDayOfWeekForDailyRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Repeat.
        /// </summary>
        internal static string SchedulerStringId_RecurrenceEditPage_EndRepeat {
            get {
                return ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_EndRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string SchedulerStringId_RecurrenceEditPage_Frequency {
            get {
                return ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string SchedulerStringId_RecurrenceEditPage_Repeat {
            get {
                return ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat On.
        /// </summary>
        internal static string SchedulerStringId_RecurrenceEditPage_RepeatOn {
            get {
                return ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_RepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        internal static string SchedulerStringId_ReminderAddPage_Custom {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderAddPage_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At time of event.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_AtTimeOfEvent {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_AtTimeOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Custom {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Day {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Days {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Hour {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Hours {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Minute {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Minutes {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Second {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_Seconds {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} before.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_TimeBefore {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_TimeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} before start.
        /// </summary>
        internal static string SchedulerStringId_ReminderTextFormatter_TimeBeforeStart {
            get {
                return ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_TimeBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string SchedulerStringId_TextRecurrenceTypeDaily {
            get {
                return ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        internal static string SchedulerStringId_TextRecurrenceTypeHourly {
            get {
                return ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutely.
        /// </summary>
        internal static string SchedulerStringId_TextRecurrenceTypeMinutely {
            get {
                return ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeMinutely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string SchedulerStringId_TextRecurrenceTypeMonthly {
            get {
                return ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string SchedulerStringId_TextRecurrenceTypeNever {
            get {
                return ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string SchedulerStringId_TextRecurrenceTypeWeekly {
            get {
                return ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string SchedulerStringId_TextRecurrenceTypeYearly {
            get {
                return ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string SchedulerStringId_TimeZoneSelectPage_SearchBarPlaceholderText {
            get {
                return ResourceManager.GetString("SchedulerStringId.TimeZoneSelectPage_SearchBarPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string SchedulerStringId_WeekRadioGroup_Every {
            get {
                return ResourceManager.GetString("SchedulerStringId.WeekRadioGroup_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        internal static string SchedulerStringId_WeekRadioGroup_WeekOrWeeks {
            get {
                return ResourceManager.GetString("SchedulerStringId.WeekRadioGroup_WeekOrWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day of.
        /// </summary>
        internal static string SchedulerStringId_YearRadioGroup_DayOf {
            get {
                return ResourceManager.GetString("SchedulerStringId.YearRadioGroup_DayOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string SchedulerStringId_YearRadioGroup_Every {
            get {
                return ResourceManager.GetString("SchedulerStringId.YearRadioGroup_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of every.
        /// </summary>
        internal static string SchedulerStringId_YearRadioGroup_OfEvery {
            get {
                return ResourceManager.GetString("SchedulerStringId.YearRadioGroup_OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        internal static string SchedulerStringId_YearRadioGroup_The {
            get {
                return ResourceManager.GetString("SchedulerStringId.YearRadioGroup_The", resourceCulture);
            }
        }
    }
}
