'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace LocalizeApplication.Resources.Localization

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    '''   This class was generated by MSBuild using the GenerateResource task.
    '''   To add or remove a member, edit your .resx file then rerun MSBuild.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class ApplicationStrings

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(LocalizeApplication.Resources.Localization.ApplicationStrings.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LocalizeApplication.Resources.Localization.ApplicationStrings", GetType(LocalizeApplication.Resources.Localization.ApplicationStrings).Assembly)
                    LocalizeApplication.Resources.Localization.ApplicationStrings.resourceMan = temp
                End If

                Return LocalizeApplication.Resources.Localization.ApplicationStrings.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return LocalizeApplication.Resources.Localization.ApplicationStrings.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                LocalizeApplication.Resources.Localization.ApplicationStrings.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Home.
        ''' </summary>
        Friend Shared ReadOnly Property NumberType_Home As String
            Get
                Return LocalizeApplication.Resources.Localization.ApplicationStrings.ResourceManager.GetString("NumberType_Home", LocalizeApplication.Resources.Localization.ApplicationStrings.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Mobile.
        ''' </summary>
        Friend Shared ReadOnly Property NumberType_Mobile As String
            Get
                Return LocalizeApplication.Resources.Localization.ApplicationStrings.ResourceManager.GetString("NumberType_Mobile", LocalizeApplication.Resources.Localization.ApplicationStrings.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Unknown.
        ''' </summary>
        Friend Shared ReadOnly Property NumberType_Unknown As String
            Get
                Return LocalizeApplication.Resources.Localization.ApplicationStrings.ResourceManager.GetString("NumberType_Unknown", LocalizeApplication.Resources.Localization.ApplicationStrings.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Work.
        ''' </summary>
        Friend Shared ReadOnly Property NumberType_Work As String
            Get
                Return LocalizeApplication.Resources.Localization.ApplicationStrings.ResourceManager.GetString("NumberType_Work", LocalizeApplication.Resources.Localization.ApplicationStrings.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Call History.
        ''' </summary>
        Friend Shared ReadOnly Property ViewTitle As String
            Get
                Return LocalizeApplication.Resources.Localization.ApplicationStrings.ResourceManager.GetString("ViewTitle", LocalizeApplication.Resources.Localization.ApplicationStrings.resourceCulture)
            End Get
        End Property
    End Class
End Namespace
