'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace LocalizeApplication.Resources.Localization

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    '''   This class was generated by MSBuild using the GenerateResource task.
    '''   To add or remove a member, edit your .resx file then rerun MSBuild.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class DevExpressMaui

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(LocalizeApplication.Resources.Localization.DevExpressMaui.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LocalizeApplication.Resources.Localization.DevExpressMaui", GetType(LocalizeApplication.Resources.Localization.DevExpressMaui).Assembly)
                    LocalizeApplication.Resources.Localization.DevExpressMaui.resourceMan = temp
                End If

                Return LocalizeApplication.Resources.Localization.DevExpressMaui.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}: {1}.
        ''' </summary>
        Friend Shared ReadOnly Property CollectionViewStringId_GroupCaptionDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("CollectionViewStringId.GroupCaptionDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}, {1}.
        ''' </summary>
        Friend Shared ReadOnly Property CollectionViewStringId_GroupIntervalMonthDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("CollectionViewStringId.GroupIntervalMonthDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}.
        ''' </summary>
        Friend Shared ReadOnly Property CollectionViewStringId_GroupIntervalYearDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("CollectionViewStringId.GroupIntervalYearDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Older;Last Month;Earlier this Month;Three Weeks Ago;Two Weeks Ago;Last Week;;;;;;;;Yesterday;Today;Tomorrow;;;;;;;;Next Week;Two Weeks Away;Three Weeks Away;Later this Month;Next Month;Beyond Next Month;.
        ''' </summary>
        Friend Shared ReadOnly Property CollectionViewStringId_OutlookIntervals As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("CollectionViewStringId.OutlookIntervals", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Not found.
        ''' </summary>
        Friend Shared ReadOnly Property EditorStringId_ComboBox_NotFound As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("EditorStringId.ComboBox_NotFound", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Invalid input value.
        ''' </summary>
        Friend Shared ReadOnly Property EditorStringId_DataForm_ValidationExceptionMessage As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("EditorStringId.DataForm_ValidationExceptionMessage", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to CANCEL.
        ''' </summary>
        Friend Shared ReadOnly Property EditorStringId_DateEdit_Picker_CANCEL As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("EditorStringId.DateEdit_Picker_CANCEL", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to OK.
        ''' </summary>
        Friend Shared ReadOnly Property EditorStringId_DateEdit_Picker_OK As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("EditorStringId.DateEdit_Picker_OK", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to AVG.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_Caption_SummaryAverage As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.Caption_SummaryAverage", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to COUNT.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_Caption_SummaryCount As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.Caption_SummaryCount", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to VAL.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_Caption_SummaryCustom As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.Caption_SummaryCustom", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to MAX.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_Caption_SummaryMax As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.Caption_SummaryMax", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to MIN.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_Caption_SummaryMin As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.Caption_SummaryMin", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to  .
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_Caption_SummaryNone As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.Caption_SummaryNone", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to SUM.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_Caption_SummarySum As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.Caption_SummarySum", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Edit Values.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_EditorFormPage_EditValues As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.EditorFormPage_EditValues", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Save.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_EditorFormPage_Save As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.EditorFormPage_Save", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Older;Last Month;Earlier this Month;Three Weeks Ago;Two Weeks Ago;Last Week;;;;;;;;Yesterday;Today;Tomorrow;;;;;;;;Next Week;Two Weeks Away;Three Weeks Away;Later this Month;Next Month;Beyond Next Month;.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_GridOutlookIntervals As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.GridOutlookIntervals", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}: {1}.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_GroupCaptionDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.GroupCaptionDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}, {1}.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_GroupIntervalMonthDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.GroupIntervalMonthDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_GroupIntervalYearDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.GroupIntervalYearDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}={2}.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_GroupSummaryCountDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.GroupSummaryCountDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {1}: {0}={2}.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_GroupSummaryDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.GroupSummaryDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}: {1}.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_GroupSummaryShortDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.GroupSummaryShortDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0}={2}.
        ''' </summary>
        Friend Shared ReadOnly Property GridStringId_TotalSummaryDisplayFormat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("GridStringId.TotalSummaryDisplayFormat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to day.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Day As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Day", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to days.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Days As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Days", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to hour.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Hour As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Hour", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to hours.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Hours As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Hours", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to minute.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Minute As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Minute", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to minutes.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Minutes As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Minutes", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to week.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Week As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Week", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to weeks.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Abbr_Weeks As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Abbr_Weeks", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Label.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Appointment_Label As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Appointment_Label", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Reminder.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Appointment_Reminder As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Appointment_Reminder", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Status.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Appointment_Status As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Appointment_Status", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Repeat {0}.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentDetailFormat_Recurrence As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentDetailFormat_Recurrence", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Status: {0}.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentDetailFormat_Status As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentDetailFormat_Status", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Yes.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_AcceptAppointmentRemoveAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_AcceptAppointmentRemoveAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cancel.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_CancelAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_CancelAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to No.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_CancelAppointmentRemoveAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_CancelAppointmentRemoveAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Edit Appointment.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_EditAppointmentTitle As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditAppointmentTitle", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Change this and all future appointments.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_EditFutureOccurrencesAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditFutureOccurrencesAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Change this appointment only.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_EditOccurrenceAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditOccurrenceAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Change all appointments in the series.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_EditPatternAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_EditPatternAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to New Appointment.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_NewAppointmentTitle As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_NewAppointmentTitle", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Reminder Customization.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_ReminderCustomization As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_ReminderCustomization", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Delete appointment?.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_RemoveAppointmentTitle As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemoveAppointmentTitle", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Delete this and all future appointments.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_RemoveFutureOccurrencesAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemoveFutureOccurrencesAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Delete this appointment only.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_RemoveOccurrenceAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemoveOccurrenceAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Delete all appointments in the series.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_RemovePatternAction As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_RemovePatternAction", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to This is a recurring appointment..
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEdit_SelectAppointmentTypeTitle As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEdit_SelectAppointmentTypeTitle", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Add another reminder.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEditPage_AddAnotherReminder As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_AddAnotherReminder", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Add a reminder.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEditPage_AddReminder As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_AddReminder", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to All day.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEditPage_AllDay As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_AllDay", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Label.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEditPage_Label As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_Label", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Repeat.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEditPage_Repeat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_Repeat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Status.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEditPage_Status As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_Status", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Appointment name.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentEditPage_SubjectPlaceholder As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentEditPage_SubjectPlaceholder", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Anniversary.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_Anniversary As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Anniversary", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Birthday.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_Birthday As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Birthday", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Business.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_Business As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Business", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Important.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_Important As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Important", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Must Attend.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_MustAttend As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_MustAttend", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Needs Preparation.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_NeedsPreparation As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_NeedsPreparation", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to None.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_None As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_None", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Personal.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_Personal As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Personal", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Phone Call.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_PhoneCall As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_PhoneCall", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Travel Required.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_TravelRequired As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_TravelRequired", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Vacation.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_AppointmentLabel_Vacation As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.AppointmentLabel_Vacation", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Busy.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_Busy As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_Busy", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Free.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_Free As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_Free", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Out Of Office.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_OutOfOffice As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_OutOfOffice", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Tentative.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_Tentative As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_Tentative", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Day.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekDaysEveryDay As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekDaysEveryDay", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Weekend day.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekDaysWeekendDays As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekDaysWeekendDays", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Weekday.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekDaysWorkDays As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekDaysWorkDays", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to First.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekOfMonthFirst As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthFirst", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Fourth.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekOfMonthFourth As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthFourth", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Last.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekOfMonthLast As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthLast", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Second.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekOfMonthSecond As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthSecond", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Third.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WeekOfMonthThird As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WeekOfMonthThird", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Working Elsewhere.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Caption_WorkingElsewhere As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Caption_WorkingElsewhere", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to After.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_CommonRadioGroup_After As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_After", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Never.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_CommonRadioGroup_Never As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_Never", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to occurrence(s).
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_CommonRadioGroup_Occurrences As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_Occurrences", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to On.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_CommonRadioGroup_On As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.CommonRadioGroup_On", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to day(s).
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_DayRadioGroup_DayOrDays As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.DayRadioGroup_DayOrDays", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Every.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_DayRadioGroup_Every As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.DayRadioGroup_Every", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Every weekday.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_DayRadioGroup_EveryWeekDay As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.DayRadioGroup_EveryWeekDay", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to day(s).
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_MonthRadioGroup_DayOrDays As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_DayOrDays", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Each.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_MonthRadioGroup_Each As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_Each", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to month(s).
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_MonthRadioGroup_MonthOrMonths As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_MonthOrMonths", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to of every.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_MonthRadioGroup_OfEvery As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_OfEvery", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_MonthRadioGroup_The As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.MonthRadioGroup_The", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Invalid day of week for a daily recurrence. Only WeekDays.EveryDay, WeekDays.WeekendDays and WeekDays.WorkDays are valid in this context..
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_Msg_InvalidDayOfWeekForDailyRecurrence As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.Msg_InvalidDayOfWeekForDailyRecurrence", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to End Repeat.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_RecurrenceEditPage_EndRepeat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_EndRepeat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Frequency.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_RecurrenceEditPage_Frequency As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_Frequency", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Repeat.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_RecurrenceEditPage_Repeat As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_Repeat", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Repeat On.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_RecurrenceEditPage_RepeatOn As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.RecurrenceEditPage_RepeatOn", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Custom....
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderAddPage_Custom As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderAddPage_Custom", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to At time of event.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_AtTimeOfEvent As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_AtTimeOfEvent", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Custom....
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Custom As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Custom", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to day.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Day As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Day", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to days.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Days As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Days", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to hour.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Hour As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Hour", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to hours.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Hours As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Hours", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to minute.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Minute As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Minute", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to minutes.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Minutes As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Minutes", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to second.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Second As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Second", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to seconds.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_Seconds As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_Seconds", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} before.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_TimeBefore As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_TimeBefore", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to {0} before start.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_ReminderTextFormatter_TimeBeforeStart As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.ReminderTextFormatter_TimeBeforeStart", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Daily.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TextRecurrenceTypeDaily As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeDaily", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Hourly.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TextRecurrenceTypeHourly As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeHourly", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Minutely.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TextRecurrenceTypeMinutely As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeMinutely", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Monthly.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TextRecurrenceTypeMonthly As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeMonthly", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Never.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TextRecurrenceTypeNever As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeNever", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Weekly.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TextRecurrenceTypeWeekly As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeWeekly", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Yearly.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TextRecurrenceTypeYearly As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TextRecurrenceTypeYearly", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Time Zone.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_TimeZoneSelectPage_SearchBarPlaceholderText As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.TimeZoneSelectPage_SearchBarPlaceholderText", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Every.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_WeekRadioGroup_Every As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.WeekRadioGroup_Every", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to week(s).
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_WeekRadioGroup_WeekOrWeeks As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.WeekRadioGroup_WeekOrWeeks", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to day of.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_YearRadioGroup_DayOf As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.YearRadioGroup_DayOf", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Every.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_YearRadioGroup_Every As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.YearRadioGroup_Every", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to of every.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_YearRadioGroup_OfEvery As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.YearRadioGroup_OfEvery", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to The.
        ''' </summary>
        Friend Shared ReadOnly Property SchedulerStringId_YearRadioGroup_The As String
            Get
                Return LocalizeApplication.Resources.Localization.DevExpressMaui.ResourceManager.GetString("SchedulerStringId.YearRadioGroup_The", LocalizeApplication.Resources.Localization.DevExpressMaui.resourceCulture)
            End Get
        End Property
    End Class
End Namespace
