'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace CustomLanguageResource.Resources

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    '''   This class was generated by MSBuild using the GenerateResource task.
    '''   To add or remove a member, edit your .resx file then rerun MSBuild.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class DevExpressMaui

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(CustomLanguageResource.Resources.DevExpressMaui.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CustomLanguageResource.Resources.DevExpressMaui", GetType(CustomLanguageResource.Resources.DevExpressMaui).Assembly)
                    CustomLanguageResource.Resources.DevExpressMaui.resourceMan = temp
                End If

                Return CustomLanguageResource.Resources.DevExpressMaui.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return CustomLanguageResource.Resources.DevExpressMaui.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                CustomLanguageResource.Resources.DevExpressMaui.resourceCulture = value
            End Set
        End Property
    End Class
End Namespace
